### ISSUE TITLE
License

### ISSUE THREAD

**Issue by miyamot0** [parrotgeek1/LauncherHijack#1]
Hi Hi,

I'm a researcher developing communication applications for children with disabilities (GPLv3).  I'd like to include and reference your code, as I've found its the easiest way to keep kids in a standalone, launcher mode application.  Do you have a license for this?  If it was something permissive I'd certainly be able to include it and make sure you're attributed.  Please let me know.

Thanks!

Shawn

**Comment by parrotgeek1** [comment]
Absolutely! I have a disability myself, so it's awesome that you've found a use for this. 

The license is basically "you can do whatever you want except you have to credit me somewhere in the app, including a link to the repo." The modified version doesn't have to be open source. You have to send me a link to the modified version if it is ever public, or the paper if it isn't.

**Comment by miyamot0** [comment]
Excellent.

The project (and everything I do) is full GPL, all zero-cost tools/apps for kids and families on iOS and Android.

I appreciate your work.

Best,

Shawn
