### ISSUE TITLE
I used some of your code in my project (KFUIM)

### ISSUE THREAD

**Issue by karlsecret** [parrotgeek1/LauncherHijack#3]
KFUIM is my version of LauncherHijack (with improvements) and it stands for

K indle
F ire
U ser
I nterface
M anager

link: [http://karlswebsite.uk.tn/kfuim.html](url)

**Comment by parrotgeek1** [comment]
Thanks but please follow the terms of the license. You didn't mention
launcher hijack in the app, or link to my source code or credit me. Is this
going to be open source? It doesn't have to be, I'm just wondering.

**Comment by karlsecret** [comment]
I did on the website.

**Comment by karlsecret** [comment]
Do I need to in the app.

**Comment by karlsecret** [comment]
The link is broken copy and paste the url instead.

**Comment by karlsecret** [comment]
I'm not sure if it will be open source

**Comment by parrotgeek1** [comment]
That's fine. You're following the license now.

**Comment by karlanonymous** [comment]
thank you parrotgeek1.

**Comment by karlsecret** [comment]
KFUIM is open source [https://github.com/karlsecret/KFUIM](url).

**Comment by parrotgeek1** [comment]
Cool, thanks.
