### ISSUE TITLE
You don't seem to be responding to me so I made a new acount

### ISSUE THREAD

**Issue by karlanonymous** [parrotgeek1/LauncherHijack#5]

**Comment by parrotgeek1** [comment]
it's only been a few hours. WTF. All you have to do is add the link into the app and everything will be fine

**Comment by karlsecret** [comment]
I did it on the website because I don't know how to do links in apps

**Comment by karlsecret** [comment]
the licence said project not app and in my view the download page is part of the project

**Comment by karlsecret** [comment]
I think this has been a misunderstanding

**Comment by parrotgeek1** [comment]
That's fine.
