### ISSUE TITLE
Launcherhijack crash

### ISSUE THREAD

**Issue by mkirksmith** [parrotgeek1/LauncherHijack#7]
I've used a renamed LauncherHijack to HJclone and used it to install the Nova Launcher on my 2019 Fire HD10. After a short delay the Nova homepage appears. However, the attached error message appears. Is there a way of stopping the crash? 

It's not a problem as Nova does launch, however, I thought I'd let you know in case it is useful for you.

![Launcherhijack crash](https://user-images.githubusercontent.com/60510107/73540930-12530500-4429-11ea-9249-9284a6e60a7f.jpg)

Michael

**Comment by parrotgeek1** [comment]
I do not support forks of LauncherHijack, including the one by BaronKiko.

**Comment by mkirksmith** [comment]
Hi Ethan,

OK. My apologies for bothering you. I thought that the email would be
addressed by BaronKiki. I'll now try and contact him directly.

Michael
