### ISSUE TITLE
Fire HD 8 opens FireOS-Launcher fpr a short time after pressing the home-button

### ISSUE THREAD

**Issue by NebuKa** [parrotgeek1/LauncherHijack#8]
I just installed the Nova launcher with LauncherHijack (Cloned the App) and it works somehow. 
But: Every time i press the home-button, the Fire-Launcher opens for like 5 sek. , then it switches to Nova-Launcher-Homescreen. Am I doing something wrong?
Thank your for your time :)

System: 
Fire HD 8 (8 generation)
Fire OS 6.3.1.5

**Comment by parrotgeek1** [comment]
This version of the app is not supported anymore. Please use the "launcher hijack v4" on XDA.
